<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\smol_holomyth_alternative_textures.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smol-holomyth-alternative-textures-b98da3de79e940a79c1721eb29cdbbb5
Title: Smol Holomyth, Alternative Textures.
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_208: THREE.SkinnedMesh
      Object_209: THREE.SkinnedMesh
      Object_210: THREE.SkinnedMesh
      Object_211: THREE.SkinnedMesh
      GLTF_created_4_rootJoint: THREE.Bone
    }
    materials: {
      Outline: THREE.MeshStandardMaterial
      Smolame: THREE.MeshStandardMaterial
      SmolameHead: THREE.MeshStandardMaterial
      SmolameEye: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/smol_holomyth_alternative_textures.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- Ame -->
    <T.Group scale={0.4}>
      <T is={gltf.nodes.GLTF_created_4_rootJoint} />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_208.geometry}
        material={gltf.materials.Smolame}
        skeleton={gltf.nodes.Object_208.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_209.geometry}
        material={gltf.materials.Outline}
        skeleton={gltf.nodes.Object_209.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_210.geometry}
        material={gltf.materials.SmolameHead}
        skeleton={gltf.nodes.Object_210.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_211.geometry}
        material={gltf.materials.SmolameEye}
        skeleton={gltf.nodes.Object_211.skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
