<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\smol_holomyth_alternative_textures.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smol-holomyth-alternative-textures-b98da3de79e940a79c1721eb29cdbbb5
Title: Smol Holomyth, Alternative Textures.
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_7: THREE.SkinnedMesh
      Object_8: THREE.SkinnedMesh
      Object_9: THREE.SkinnedMesh
      Object_10: THREE.SkinnedMesh
      GLTF_created_0_rootJoint: THREE.Bone
    }
    materials: {
      SmolGura: THREE.MeshStandardMaterial
      Outline: THREE.MeshStandardMaterial
      SmolguraHead: THREE.MeshStandardMaterial
      SmolguraEye: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/smol_holomyth_alternative_textures.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- Gura -->
    <T.Group scale={0.4}>
      <T is={gltf.nodes.GLTF_created_0_rootJoint} />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_7.geometry}
        material={gltf.materials.SmolGura}
        skeleton={gltf.nodes.Object_7.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_8.geometry}
        material={gltf.materials.Outline}
        skeleton={gltf.nodes.Object_8.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_9.geometry}
        material={gltf.materials.SmolguraHead}
        skeleton={gltf.nodes.Object_9.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_10.geometry}
        material={gltf.materials.SmolguraEye}
        skeleton={gltf.nodes.Object_10.skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
