<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\smol_holomyth_alternative_textures.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/smol-holomyth-alternative-textures-b98da3de79e940a79c1721eb29cdbbb5
Title: Smol Holomyth, Alternative Textures.
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_61: THREE.SkinnedMesh
      Object_62: THREE.SkinnedMesh
      Object_63: THREE.SkinnedMesh
      Object_64: THREE.SkinnedMesh
      Object_65: THREE.SkinnedMesh
      GLTF_created_1_rootJoint: THREE.Bone
    }
    materials: {
      Outline: THREE.MeshStandardMaterial
      smolina: THREE.MeshStandardMaterial
      smolinaHair: THREE.MeshStandardMaterial
      SmolinHead: THREE.MeshStandardMaterial
      SmolinaEye: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/smol_holomyth_alternative_textures.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- Ina -->
    <T.Group scale={0.4}>
      <T is={gltf.nodes.GLTF_created_1_rootJoint} />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_61.geometry}
        material={gltf.materials.smolina}
        skeleton={gltf.nodes.Object_61.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_62.geometry}
        material={gltf.materials.Outline}
        skeleton={gltf.nodes.Object_62.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_63.geometry}
        material={gltf.materials.smolinaHair}
        skeleton={gltf.nodes.Object_63.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_64.geometry}
        material={gltf.materials.SmolinHead}
        skeleton={gltf.nodes.Object_64.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_65.geometry}
        material={gltf.materials.SmolinaEye}
        skeleton={gltf.nodes.Object_65.skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
