<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\beegsmol_councilrys_-_hololive_en.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/beegsmol-councilrys-hololive-en-5517f50fd178493fa29b075d870351bd
Title: BEEGSmol CouncilRyS! - Hololive EN
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  // type $$Props = Props<THREE.Group>
  // type $$Events = Events<THREE.Group>
  // type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_116: THREE.SkinnedMesh
      Object_117: THREE.SkinnedMesh
      Object_201: THREE.SkinnedMesh
      Object_202: THREE.SkinnedMesh
      Object_204: THREE.SkinnedMesh
      Object_205: THREE.SkinnedMesh
      Object_207: THREE.SkinnedMesh
      Object_208: THREE.SkinnedMesh
      Object_288: THREE.SkinnedMesh
      Object_289: THREE.SkinnedMesh
      Object_378: THREE.SkinnedMesh
      Object_379: THREE.SkinnedMesh
      Object_462: THREE.SkinnedMesh
      Object_463: THREE.SkinnedMesh
      Object_545: THREE.SkinnedMesh
      Object_546: THREE.SkinnedMesh
      _rootJoint: THREE.Bone
      _rootJoint_1: THREE.Bone
      _rootJoint_2: THREE.Bone
      _rootJoint_3: THREE.Bone
      _rootJoint_4: THREE.Bone
      _rootJoint_5: THREE.Bone
    }
    materials: {
      outline: THREE.MeshStandardMaterial
      BeegSmolSana: THREE.MeshStandardMaterial
      BeegSmolKronii_tex: THREE.MeshStandardMaterial
      BeegSmolFauna_tex: THREE.MeshStandardMaterial
      BeegSmolBae_tex: THREE.MeshStandardMaterial
      BeegSmolMumei_tex: THREE.MeshStandardMaterial
      BeegSmolIRyS_tex: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/beegsmol_councilrys_-_hololive_en.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
    test
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
      <T is={gltf.nodes._rootJoint_1} />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_201.geometry}
        material={gltf.materials.BeegSmolKronii_tex}
        skeleton={gltf.nodes.Object_201.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_202.geometry}
        material={gltf.materials.outline}
        skeleton={gltf.nodes.Object_202.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_204.geometry}
        material={gltf.materials.BeegSmolKronii_tex}
        skeleton={gltf.nodes.Object_204.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_205.geometry}
        material={gltf.materials.outline}
        skeleton={gltf.nodes.Object_205.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_207.geometry}
        material={gltf.materials.outline}
        skeleton={gltf.nodes.Object_207.skeleton}
      />
      <T.SkinnedMesh
        geometry={gltf.nodes.Object_208.geometry}
        material={gltf.materials.BeegSmolKronii_tex}
        skeleton={gltf.nodes.Object_208.skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
