<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\smol_ame_in_an_upcycled_terrarium_hololiveen.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smol-ame-in-an-upcycled-terrarium-hololiveen-490cecc249d242188fda5ad3160a4b24
Title: Smol Ame in an Upcycled Terrarium [HololiveEn]
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Animation'
  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
      Object_37: THREE.SkinnedMesh
      Object_10: THREE.SkinnedMesh
      Object_12: THREE.SkinnedMesh
      Object_14: THREE.SkinnedMesh
      Object_16: THREE.SkinnedMesh
      Object_18: THREE.SkinnedMesh
      Object_19: THREE.SkinnedMesh
      Object_21: THREE.SkinnedMesh
      Object_23: THREE.SkinnedMesh
      Object_25: THREE.SkinnedMesh
      Object_27: THREE.SkinnedMesh
      Object_29: THREE.SkinnedMesh
      Object_31: THREE.SkinnedMesh
      Object_33: THREE.SkinnedMesh
      Object_35: THREE.SkinnedMesh
      Object_39: THREE.SkinnedMesh
      Object_41: THREE.SkinnedMesh
      Object_65: THREE.SkinnedMesh
      Object_67: THREE.SkinnedMesh
      GLTF_created_0_rootJoint: THREE.Bone
      GLTF_created_1_rootJoint: THREE.Bone
    }
    materials: {
      pasokon: THREE.MeshStandardMaterial
      terrarium1: THREE.MeshStandardMaterial
      terrarium1ame: THREE.MeshStandardMaterial
      terrarium1ameoutline: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/smol_ame_in_an_upcycled_terrarium_hololiveen.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="pasokon_1">
              <T.Mesh name="Object_4" geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.pasokon} />
              <T.Mesh name="Object_5" geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.terrarium1} />
            </T.Group>
            <T.Group name="amelia_37" position={[-0.2, 0.9, 0]} rotation={[0, 0.86, 0]}>
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.Group name="armies_21" />
                <T.Group name="armies001_22" />
                <T.Group name="bode_23" />
                <T.Group name="bode001_24" />
                <T.Group name="Cylinder003_25" />
                <T.Group name="Cylinder004_26" />
                <T.Group name="eyea_27" />
                <T.Group name="feets_28" />
                <T.Group name="feets001_29" />
                <T.Group name="guitar_30" />
                <T.Group name="guitar001_31" />
                <T.Group name="hair_32" />
                <T.Group name="hairoutline_33" />
                <T.Group name="mouf_34" />
                <T.Group name="nogging_35" />
                <T.Group name="nogging001_36" />
                <T.SkinnedMesh
                  name="Object_37"
                  geometry={gltf.nodes.Object_37.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_37.skeleton}
                  morphTargetDictionary={gltf.nodes.Object_37.morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes.Object_37.morphTargetInfluences}
                />
                <T.SkinnedMesh
                  name="Object_10"
                  geometry={gltf.nodes.Object_10.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_10.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_12"
                  geometry={gltf.nodes.Object_12.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_12.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_14"
                  geometry={gltf.nodes.Object_14.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_14.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_16"
                  geometry={gltf.nodes.Object_16.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_16.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_18"
                  geometry={gltf.nodes.Object_18.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_18.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_19"
                  geometry={gltf.nodes.Object_19.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_19.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_21"
                  geometry={gltf.nodes.Object_21.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_21.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_23"
                  geometry={gltf.nodes.Object_23.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_23.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_25"
                  geometry={gltf.nodes.Object_25.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_25.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_27"
                  geometry={gltf.nodes.Object_27.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_27.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_29"
                  geometry={gltf.nodes.Object_29.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_29.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_31"
                  geometry={gltf.nodes.Object_31.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_31.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_33"
                  geometry={gltf.nodes.Object_33.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_33.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_35"
                  geometry={gltf.nodes.Object_35.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_35.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_39"
                  geometry={gltf.nodes.Object_39.geometry}
                  material={gltf.materials.terrarium1ame}
                  skeleton={gltf.nodes.Object_39.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_41"
                  geometry={gltf.nodes.Object_41.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_41.skeleton}
                />
              </T.Group>
            </T.Group>
            <T.Group name="isopod002_49" position={[0, 0.86, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
              <T.Group name="GLTF_created_1">
                <T is={gltf.nodes.GLTF_created_1_rootJoint} />
                <T.Group name="isopod_47" />
                <T.Group name="isopod001_48" />
                <T.SkinnedMesh
                  name="Object_65"
                  geometry={gltf.nodes.Object_65.geometry}
                  material={gltf.materials.terrarium1}
                  skeleton={gltf.nodes.Object_65.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_67"
                  geometry={gltf.nodes.Object_67.geometry}
                  material={gltf.materials.terrarium1ameoutline}
                  skeleton={gltf.nodes.Object_67.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
