<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\code\holo\static\models\space_ame_camping_-_amelia_watson_hololive.glb --root /models/ --types --printwidth 120 --precision 2
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-ame-camping-amelia-watson-hololive-56ede5352988499d92892fed6061388e
Title: Space Ame Camping - Amelia Watson Hololive
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Animation'
  type GLTFResult = {
    nodes: {
      Object_4: THREE.Mesh
      mesh_17: THREE.Mesh
      Object_40: THREE.Mesh
      Object_6: THREE.Mesh
      Object_8: THREE.Mesh
      mesh_3: THREE.Mesh
      Object_12: THREE.Mesh
      Object_14: THREE.Mesh
      Object_16: THREE.Mesh
      Object_18: THREE.Mesh
      Object_20: THREE.Mesh
      Object_22: THREE.Mesh
      Object_24: THREE.Mesh
      Object_26: THREE.Mesh
      Object_28: THREE.Mesh
      Object_30: THREE.Mesh
      Object_32: THREE.Mesh
      Object_34: THREE.Mesh
      Object_36: THREE.Mesh
      mesh_19: THREE.Mesh
      Object_44: THREE.Mesh
      Object_57: THREE.SkinnedMesh
      Object_59: THREE.SkinnedMesh
      Object_67: THREE.SkinnedMesh
      Object_69: THREE.SkinnedMesh
      Object_49: THREE.SkinnedMesh
      Object_50: THREE.SkinnedMesh
      Object_52: THREE.SkinnedMesh
      Object_54: THREE.SkinnedMesh
      Object_55: THREE.SkinnedMesh
      Object_61: THREE.SkinnedMesh
      Object_63: THREE.SkinnedMesh
      Object_64: THREE.SkinnedMesh
      Object_65: THREE.SkinnedMesh
      Object_71: THREE.SkinnedMesh
      Object_72: THREE.SkinnedMesh
      Object_74: THREE.SkinnedMesh
      Object_75: THREE.SkinnedMesh
      Object_77: THREE.SkinnedMesh
      Object_78: THREE.SkinnedMesh
      Object_80: THREE.SkinnedMesh
      Object_82: THREE.SkinnedMesh
      Object_83: THREE.SkinnedMesh
      Object_85: THREE.SkinnedMesh
      Object_86: THREE.SkinnedMesh
      GLTF_created_0_rootJoint: THREE.Bone
    }
    materials: {
      ['Material.002']: THREE.MeshStandardMaterial
      fire: THREE.MeshStandardMaterial
      moon: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      smoke: THREE.MeshStandardMaterial
      spaceglow: THREE.MeshStandardMaterial
      spaceame: THREE.MeshStandardMaterial
      spaceameface: THREE.MeshStandardMaterial
      outline: THREE.MeshStandardMaterial
      ['helmet.002']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/space_ame_camping_-_amelia_watson_hololive.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.27}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Sphere_1" position={[-0.39, -23.8, -0.43]} rotation={[0, -Math.PI / 2, 0]} scale={63.3}>
              <T.Mesh
                name="Object_4"
                geometry={gltf.nodes.Object_4.geometry}
                material={gltf.materials['Material.002']}
              />
            </T.Group>
            <T.Group
              name="Icosphere_20"
              position={[-1.27, -0.64, 2.57]}
              rotation={[0.03, 0.44, 0.13]}
              scale={[0.63, 0.55, 0.45]}
            >
              <T.Mesh
                name="mesh_17"
                geometry={gltf.nodes.mesh_17.geometry}
                material={gltf.materials.fire}
                morphTargetDictionary={gltf.nodes.mesh_17.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_17.morphTargetInfluences}
              />
            </T.Group>
            <T.Group name="Cylinder001_21" position={[-0.93, 0.54, 0.12]} rotation={[0.75, 0.56, 0.19]}>
              <T.Mesh name="Object_40" geometry={gltf.nodes.Object_40.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Sphere001_3"
              position={[-1.43, -3.2, -1.04]}
              rotation={[0.15, -0.89, -0.07]}
              scale={[47.44, 40.44, 50.62]}
            >
              <T.Mesh name="Object_6" geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group name="Cylinder_5" position={[0, -0.77, 0]}>
              <T.Mesh name="Object_8" geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="greengrass_tuft004_6"
              position={[-6.34, -3.43, 4.28]}
              rotation={[0.15, -0.31, 0.14]}
              scale={[5.02, 3.6, 5.02]}
            >
              <T.Mesh
                name="mesh_3"
                geometry={gltf.nodes.mesh_3.geometry}
                material={gltf.materials['Material.001']}
                morphTargetDictionary={gltf.nodes.mesh_3.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_3.morphTargetInfluences}
              />
            </T.Group>
            <T.Group
              name="Cube003_7"
              position={[-0.85, -0.43, 2.14]}
              rotation={[-1.87, 0.7, 2.13]}
              scale={[0.82, 0.72, 0.74]}
            >
              <T.Mesh name="Object_12" geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube017_8"
              position={[1.19, -2.28, -5.32]}
              rotation={[2.04, -1.22, 2.65]}
              scale={[3.25, 4.22, 3.26]}
            >
              <T.Mesh name="Object_14" geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube018_9"
              position={[1.77, -1.46, -3.42]}
              rotation={[0.31, -0.18, 0.32]}
              scale={[2.37, 2.36, 1.54]}
            >
              <T.Mesh name="Object_16" geometry={gltf.nodes.Object_16.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube019_10"
              position={[-12.6, -2.75, -1.58]}
              rotation={[0.73, 0.82, -0.15]}
              scale={[2.37, 2.36, 1.54]}
            >
              <T.Mesh name="Object_18" geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube020_11"
              position={[-5.32, -0.96, -5.73]}
              rotation={[0.73, 0.77, -0.17]}
              scale={[3.76, 3.73, 2.45]}
            >
              <T.Mesh name="Object_20" geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube021_12"
              position={[-0.92, -0.77, -3.53]}
              rotation={[0.83, -0.91, 1.14]}
              scale={[2.37, 2.36, 1.54]}
            >
              <T.Mesh name="Object_22" geometry={gltf.nodes.Object_22.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube022_13"
              position={[-3.82, -0.77, -3.32]}
              rotation={[2.65, -0.29, -2.86]}
              scale={[2.37, 2.36, 1.54]}
            >
              <T.Mesh name="Object_24" geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube023_14"
              position={[2.88, -1.32, -0.86]}
              rotation={[0.78, -1.28, 1.14]}
              scale={[1.21, 1.2, 0.79]}
            >
              <T.Mesh name="Object_26" geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube024_15"
              position={[-6.41, -1.48, 0.44]}
              rotation={[2.79, -0.74, 2.94]}
              scale={[1.85, 1.83, 1.2]}
            >
              <T.Mesh name="Object_28" geometry={gltf.nodes.Object_28.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube025_16"
              position={[-3.88, -2.49, 3.98]}
              rotation={[0.88, -1.03, 0.74]}
              scale={[2.31, 2.29, 1.5]}
            >
              <T.Mesh name="Object_30" geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube026_17"
              position={[4, -2.16, 0.99]}
              rotation={[1.04, -0.99, 0.92]}
              scale={[2.31, 2.29, 1.5]}
            >
              <T.Mesh name="Object_32" geometry={gltf.nodes.Object_32.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube027_18"
              position={[-11.03, -2.13, -9.05]}
              rotation={[2.37, 0.87, -2.07]}
              scale={[5.02, 4.98, 3.26]}
            >
              <T.Mesh name="Object_34" geometry={gltf.nodes.Object_34.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group
              name="Cube028_19"
              position={[-10.29, -0.36, -19.86]}
              rotation={[0.68, -0.4, 0.81]}
              scale={[5.02, 4.98, 3.26]}
            >
              <T.Mesh name="Object_36" geometry={gltf.nodes.Object_36.geometry} material={gltf.materials.moon} />
            </T.Group>
            <T.Group name="Cylinder002_22" position={[-4.24, 1.92, -13.03]}>
              <T.Mesh
                name="mesh_19"
                geometry={gltf.nodes.mesh_19.geometry}
                material={gltf.materials.smoke}
                morphTargetDictionary={gltf.nodes.mesh_19.morphTargetDictionary}
                morphTargetInfluences={gltf.nodes.mesh_19.morphTargetInfluences}
              />
            </T.Group>
            <T.Group name="Plane_24" position={[-22.77, -25.08, -21.01]} rotation={[0.61, -0.5, -0.99]} scale={37.93}>
              <T.Mesh name="Object_44" geometry={gltf.nodes.Object_44.geometry} material={gltf.materials.spaceglow} />
            </T.Group>
            <T.Group name="Armature_93" position={[0, -0.73, 0]}>
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.Group name="arms_78" />
                <T.Group name="backpack_79" />
                <T.Group name="belt_80" />
                <T.Group name="brows_81" />
                <T.Group name="eyes_82" />
                <T.Group name="glass_83" />
                <T.Group name="hair_84" />
                <T.Group name="head_85" />
                <T.Group name="head001_86" />
                <T.Group name="helmet_87" />
                <T.Group name="helmet001_88" />
                <T.Group name="legs_89" />
                <T.Group name="neck_90" />
                <T.Group name="scarf_91" />
                <T.Group name="torso_92" />
                <T.SkinnedMesh
                  name="Object_57"
                  geometry={gltf.nodes.Object_57.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_57.skeleton}
                  morphTargetDictionary={gltf.nodes.Object_57.morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes.Object_57.morphTargetInfluences}
                />
                <T.SkinnedMesh
                  name="Object_59"
                  geometry={gltf.nodes.Object_59.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_59.skeleton}
                  morphTargetDictionary={gltf.nodes.Object_59.morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes.Object_59.morphTargetInfluences}
                />
                <T.SkinnedMesh
                  name="Object_67"
                  geometry={gltf.nodes.Object_67.geometry}
                  material={gltf.materials.spaceameface}
                  skeleton={gltf.nodes.Object_67.skeleton}
                  morphTargetDictionary={gltf.nodes.Object_67.morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes.Object_67.morphTargetInfluences}
                />
                <T.SkinnedMesh
                  name="Object_69"
                  geometry={gltf.nodes.Object_69.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_69.skeleton}
                  morphTargetDictionary={gltf.nodes.Object_69.morphTargetDictionary}
                  morphTargetInfluences={gltf.nodes.Object_69.morphTargetInfluences}
                />
                <T.SkinnedMesh
                  name="Object_49"
                  geometry={gltf.nodes.Object_49.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_49.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_50"
                  geometry={gltf.nodes.Object_50.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_50.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_52"
                  geometry={gltf.nodes.Object_52.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_52.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_54"
                  geometry={gltf.nodes.Object_54.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_54.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_55"
                  geometry={gltf.nodes.Object_55.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_55.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_61"
                  geometry={gltf.nodes.Object_61.geometry}
                  material={gltf.materials['helmet.002']}
                  skeleton={gltf.nodes.Object_61.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_63"
                  geometry={gltf.nodes.Object_63.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_63.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_64"
                  geometry={gltf.nodes.Object_64.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_64.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_65"
                  geometry={gltf.nodes.Object_65.geometry}
                  material={gltf.materials['helmet.002']}
                  skeleton={gltf.nodes.Object_65.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_71"
                  geometry={gltf.nodes.Object_71.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_71.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_72"
                  geometry={gltf.nodes.Object_72.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_72.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_74"
                  geometry={gltf.nodes.Object_74.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_74.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_75"
                  geometry={gltf.nodes.Object_75.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_75.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_77"
                  geometry={gltf.nodes.Object_77.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_77.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_78"
                  geometry={gltf.nodes.Object_78.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_78.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_80"
                  geometry={gltf.nodes.Object_80.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_80.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_82"
                  geometry={gltf.nodes.Object_82.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_82.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_83"
                  geometry={gltf.nodes.Object_83.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_83.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_85"
                  geometry={gltf.nodes.Object_85.geometry}
                  material={gltf.materials.spaceame}
                  skeleton={gltf.nodes.Object_85.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_86"
                  geometry={gltf.nodes.Object_86.geometry}
                  material={gltf.materials.outline}
                  skeleton={gltf.nodes.Object_86.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
